"""artisan

Revision ID: 3e1c8c2bb58a
Revises: 
Create Date: 2026-06-05 20:16:52.210029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_artisan'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artisan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('forme_juridique', sa.String(length=10), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=False),
    sa.Column('numero_tva_intra', sa.String(length=20), nullable=False),
    sa.Column('code_naf', sa.String(length=5), nullable=True),
    sa.Column('adresse_rue', sa.String(length=255), nullable=False),
    sa.Column('adresse_complement', sa.String(length=255), nullable=True),
    sa.Column('adresse_cp', sa.String(length=5), nullable=False),
    sa.Column('adresse_ville', sa.String(length=100), nullable=False),
    sa.Column('adresse_pays', sa.String(length=2), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('nom_banque', sa.String(length=100), nullable=True),
    sa.Column('mentions_assurance_decennale', sa.Text(), nullable=True),
    sa.Column('mentions_garantie_biennale', sa.Text(), nullable=True),
    sa.Column('logo_blob', sa.LargeBinary(), nullable=True),
    sa.Column('signature_blob', sa.LargeBinary(), nullable=True),
    sa.Column('delai_grace_jours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siret', name='uq_artisan_siret')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artisan')
    # ### end Alembic commands ###
