"""client

Revision ID: db7cfe492d55
Revises: 0001_artisan
Create Date: 2026-06-05 20:24:46.326007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_client'
down_revision: Union[str, None] = '0001_artisan'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artisan_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('nom_ou_raison', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('numero_tva_intra', sa.String(length=20), nullable=True),
    sa.Column('adresse_rue', sa.String(length=255), nullable=False),
    sa.Column('adresse_complement', sa.String(length=255), nullable=True),
    sa.Column('adresse_cp', sa.String(length=5), nullable=False),
    sa.Column('adresse_ville', sa.String(length=100), nullable=False),
    sa.Column('adresse_pays', sa.String(length=2), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_artisan_id'), ['artisan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_artisan_id'))

    op.drop_table('client')
    # ### end Alembic commands ###
