"""devis

Revision ID: 0003_devis
Revises: 0002_client
Create Date: 2026-06-05 20:28:44.583461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_devis'
down_revision: Union[str, None] = '0002_client'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artisan_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('date_validite', sa.Date(), nullable=False),
    sa.Column('objet', sa.String(length=500), nullable=False),
    sa.Column('devis_global_json', sa.JSON(), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_acceptation', sa.DateTime(), nullable=True),
    sa.Column('signature_client_blob', sa.LargeBinary(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devis_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devis_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devis_client_id'))
        batch_op.drop_index(batch_op.f('ix_devis_artisan_id'))

    op.drop_table('devis')
    # ### end Alembic commands ###
