"""facture_compteur

Revision ID: 7b7b9baf7c6a
Revises: 0003_devis
Create Date: 2026-06-05 20:37:37.031269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_facture_compteur'
down_revision: Union[str, None] = '0003_devis'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compteur',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artisan_id', sa.String(length=36), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=5), nullable=False),
    sa.Column('valeur_courante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artisan_id', 'annee', 'type', name='uq_compteur_artisan_annee_type')
    )
    with op.batch_alter_table('compteur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compteur_artisan_id'), ['artisan_id'], unique=False)

    op.create_table('facture',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artisan_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('devis_id', sa.String(length=36), nullable=True),
    sa.Column('facture_remplacee_id', sa.String(length=36), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=5), nullable=False),
    sa.Column('statut', sa.String(length=25), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('objet', sa.String(length=500), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acompte_montant_ht', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_du_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode_paiement', sa.String(length=5), nullable=True),
    sa.Column('conditions_paiement', sa.Text(), nullable=True),
    sa.Column('reference_devis', sa.String(length=20), nullable=True),
    sa.Column('motif_avoir', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('facturx_xml_path', sa.String(length=500), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.ForeignKeyConstraint(['facture_remplacee_id'], ['facture.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', name='uq_facture_numero')
    )
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facture_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facture_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facture_devis_id'), ['devis_id'], unique=False)

    op.create_table('facture_ligne',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facture_id', sa.String(length=36), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=500), nullable=False),
    sa.Column('reference_article', sa.String(length=50), nullable=True),
    sa.Column('quantite', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unite', sa.String(length=5), nullable=False),
    sa.Column('prix_unitaire_ht', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('montant_ht_ligne', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('categorie_tva', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['facture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facture_ligne', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facture_ligne_facture_id'), ['facture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facture_ligne', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facture_ligne_facture_id'))

    op.drop_table('facture_ligne')
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facture_devis_id'))
        batch_op.drop_index(batch_op.f('ix_facture_client_id'))
        batch_op.drop_index(batch_op.f('ix_facture_artisan_id'))

    op.drop_table('facture')
    with op.batch_alter_table('compteur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compteur_artisan_id'))

    op.drop_table('compteur')
    # ### end Alembic commands ###
