"""avenant_paiement_audit

Revision ID: e071062c77d5
Revises: 0004_facture_compteur
Create Date: 2026-06-05 20:50:12.349968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_avenant_paiement_audit'
down_revision: Union[str, None] = '0004_facture_compteur'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artisan_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('avenant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('devis_origine_id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('objet', sa.String(length=500), nullable=False),
    sa.Column('lignes_supplementaires_json', sa.JSON(), nullable=False),
    sa.Column('montant_ht_supplementaire', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_acceptation', sa.DateTime(), nullable=True),
    sa.Column('signature_client_blob', sa.LargeBinary(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devis_origine_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('avenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avenant_devis_origine_id'), ['devis_origine_id'], unique=False)

    op.create_table('paiement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facture_id', sa.String(length=36), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=5), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['facture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paiement_facture_id'), ['facture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paiement_facture_id'))

    op.drop_table('paiement')
    with op.batch_alter_table('avenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avenant_devis_origine_id'))

    op.drop_table('avenant')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_artisan_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
