"""devis_plan_image

Revision ID: bd48b2ab97f0
Revises: 0005_avenant_paiement_audit
Create Date: 2026-06-08 14:51:35.247930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_devis_plan_image'
down_revision: Union[str, None] = '0005_avenant_paiement_audit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_image_blob', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('plan_image_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('plan_image_mime', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_column('plan_image_mime')
        batch_op.drop_column('plan_image_name')
        batch_op.drop_column('plan_image_blob')

    # ### end Alembic commands ###
